[natural_gas]

cost=5  # some dummy data

[elec_config]
input_path='input/electricity/cem_inputs'
output_path='output'
regional_exchange=true
capacity_expansion=true
expansion_learning_type='linear'
reserve_margin_required=true
spinning_reserve_required=true
ramping_required=true
aggregated_years=true